### ISSUE TITLE
Publish `chrischinchilla.vscode-pandoc` to Open VSX

### ISSUE THREAD

**Issue by goyalyashpal** [ChrisChinchilla/vscode-pandoc#16]
Hi!
do u have any plans to publish ur extension on open-vsx??
See this for more details: [chrischinchilla.vscode-pandoc](https://open-vsx.org/vscode/item?itemName=chrischinchilla.vscode-pandoc)
Thanks!

**Comment by yashpalgoyal1304** [comment]
pinging @ChrisChinchilla 😃

**Comment by ChrisChinchilla** [comment]
@yashpalgoyal1304 I didn't have any plans until now as as I had never heard of it, but I can take a look when I get a moment.

**Comment by yashpalgoyal1304** [comment]
> never heard of it

**TL;DR:** VSCodium (FOSS build of proprietary VSCode) uses open-vsx for extensions as it can't use the MS' marketplace due to T&C limitations

> when I get a moment.

yeah sure :)

**Comment by goyalyashpal** [comment]
Dear extension author,
Please publish this extension to the Open VSX marketplace.

## Context

Unfortunately, as Microsoft prohibits usages of the Microsoft marketplace by any other products or redistribution of `.vsix` files from it, in order to use VS Code extensions in non-Microsoft products, we kindly ask that you take ownership of the VS Code extension namespace in [Open VSX](https://open-vsx.org/) and publish this extension on Open VSX.

## What is Open VSX? Why does it exist?

Open VSX is a vendor neutral alternative to the MS marketplace used by most other derivatives of VS Code like [VSCodium](https://vscodium.com/), [Gitpod](https://www.gitpod.io), [OpenVSCode](https://github.com/gitpod-io/openvscode-server), [Theia](https://theia-ide.org/)-based IDEs, and so on.

You can read on about Open VSX at the Eclipse Foundation's [Open VSX FAQ](https://www.eclipse.org/legal/open-vsx-registry-faq/).

## How can you publish to Open VSX?

The docs to publish an extension can be found [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). This process is straightforward and shouldn't take too long. Essentially, you need an authentication token and to execute the `ovsx publish` command to publish your extension. There's also [a doc](https://github.com/open-vsx/publish-extensions/blob/master/docs/direct_publish_setup.md) explaining the whole process with an example GitHub Action workflow.

**Comment by ChrisChinchilla** [comment]
@goyalyashpal I thought this was already working, but recently discovered that none of my extensions were publishing on the automated jobs I created. Now there are again! 🥳
