### ISSUE TITLE
extension using wrong version of pandoc

### ISSUE THREAD

**Issue by badralbanna** [ChrisChinchilla/vscode-pandoc#2]
I keep running into a problem where it runs the wrong version of pandoc vis whatever PATH is being used by the shell behind the scenes (I'm on macOS want to use my homebrew version but it keeps picking the one from anaconda python). It would be great to be able to have the option to explicitly specify which pandoc the extension uses to avoid this in the future. Thanks!

**Comment by cands** [comment]
I have a similar problem and also want to be able to explicitly set the pandoc version. In my case the extension is attempting to use `/bin/sh/pandoc` but that does not exist and thus an error is generated. I would like to use the anaconda version `/Users/*******/anaconda3/bin/pandoc`

**Comment by feeeper** [comment]
@ChrisChinchilla I fix it in my fork of the repo. So I can copy my changes here.

**Comment by ChrisChinchilla** [comment]
I completely missed this issue, sorry! I have allowed for using custom paths in similar extensions, so can add here, or if you have a PR @feeeper then please open one and I'll add it in :)

**Comment by feeeper** [comment]
@ChrisChinchilla Ok, I'm going to PR this feature later this week 👍

**Comment by ChrisChinchilla** [comment]
Closed by #4
